[package]
authors = ["Ashkan Kiani <ashkan.k.kiani@gmail.com>"]
name = "mintrs"
version = "0.1.0"

[dependencies]
docopt = "0.6.78"
docopt_macros = "0.6.78"
eventual = "0.1.4"
hyper = "0.7.0"
lazy_static = "0.1.15"
serde = "0.6.6"
serde_json = "0.6.0"
serde_macros = "0.6.5"
url = "0.5.0"
